# Generated by Django 4.2.6 on 2024-02-18 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('a', 'آپارتمانی'), ('v', 'ویلایی')], default='a', max_length=1, verbose_name='نوع منزل')),
                ('state', models.CharField(default='گیلان', max_length=100, verbose_name='استان')),
                ('city', models.CharField(default='رشت', max_length=100, verbose_name='شهر')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='منطقه')),
                ('street', models.CharField(default='اصلی', max_length=100, verbose_name='خیابان')),
                ('main_alley', models.CharField(blank=True, max_length=100, verbose_name='کوچه اصلی')),
                ('side_alley', models.CharField(blank=True, max_length=100, verbose_name='کوچه فرعی')),
                ('building_number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='شماره پلاک')),
                ('building_name', models.CharField(blank=True, max_length=100, verbose_name='نام ساختمان')),
                ('floor', models.PositiveSmallIntegerField(blank=True, verbose_name='طبقه')),
                ('unit', models.PositiveSmallIntegerField(default=1, verbose_name='واحد')),
                ('elevator', models.BooleanField(default=True, verbose_name='آسانسور')),
                ('parking', models.BooleanField(default=True, verbose_name='پارکینگ')),
                ('warehouse', models.BooleanField(default=True, verbose_name='انبار')),
                ('swimming_pool', models.BooleanField(default=False, verbose_name='استخر')),
                ('year_created', models.DateField(default=1402, verbose_name='سال ساخت')),
                ('area', models.PositiveSmallIntegerField(default=80, validators=[django.core.validators.MinValueValidator(45), django.core.validators.MaxValueValidator(900)], verbose_name='مساحت')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات بیشتر')),
            ],
            options={
                'unique_together': {('side_alley', 'building_number', 'building_name', 'floor', 'unit')},
            },
        ),
    ]
