# Generated by Django 4.2.6 on 2024-02-18 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='area',
            field=models.DecimalField(decimal_places=2, default=80, max_digits=5, validators=[django.core.validators.MinValueValidator(45), django.core.validators.MaxValueValidator(900)], verbose_name='مساحت'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='street',
            field=models.CharField(max_length=100, verbose_name='خیابان'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='unit',
            field=models.PositiveSmallIntegerField(verbose_name='واحد'),
        ),
    ]
