# Generated by Django 4.2.6 on 2024-02-18 16:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_estate_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='postal_code',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(45), django.core.validators.MaxValueValidator(900)], verbose_name='مساحت'),
        ),
    ]
