# Generated by Django 4.2.6 on 2024-02-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0005_alter_estate_year_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='slug',
            field=models.SlugField(default='<django.db.models.fields.CharField>-<django.db.models.fields.CharField>-<django.db.models.fields.CharField>-<django.db.models.fields.CharField>-<django.db.models.fields.CharField>', verbose_name='URL'),
        ),
    ]
