# Generated by Django 4.2.6 on 2024-02-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0006_estate_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='slug',
            field=models.SlugField(default='djangodbmodelsfieldscharfield', verbose_name='url'),
        ),
    ]
