# Generated by Django 4.2.6 on 2024-02-18 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0007_alter_estate_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='year',
            field=models.IntegerField(default=1399, validators=[django.core.validators.MinValueValidator(1984), django.core.validators.MaxValueValidator(2024)], verbose_name='سال ساخت'),
        ),
    ]
