# Generated by Django 4.2.6 on 2024-02-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0008_estate_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estate',
            name='year',
        ),
    ]
