# Generated by Django 4.2.6 on 2024-02-18 18:15

from django.db import migrations, models
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0009_remove_estate_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='slug',
            field=models.SlugField(default='', unique=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='estate',
            name='year_created',
            field=django_jalali.db.models.jDateField(verbose_name='سال ساخت'),
        ),
    ]
