# Generated by Django 4.2.6 on 2024-02-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0010_alter_estate_slug_alter_estate_year_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estate',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', unique=True, verbose_name='url'),
        ),
    ]
