# Generated by Django 4.2.6 on 2024-02-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('director', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('pga', models.IntegerField(blank=True)),
            ],
        ),
    ]
